# Generated by Django 5.1.15 on 2026-07-09 19:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trays_per_box",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Лотков в коробке"
                    ),
                ),
                (
                    "eggs_per_tray",
                    models.PositiveIntegerField(default=30, verbose_name="Яиц в лотке"),
                ),
                (
                    "old_debt_threshold_days",
                    models.PositiveIntegerField(
                        default=14, verbose_name="Порог «старого» долга (дней)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Настройки системы",
                "verbose_name_plural": "Настройки системы",
                "db_table": "app_settings",
            },
        ),
        migrations.CreateModel(
            name="EggType",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=100, verbose_name="Название (рус)"),
                ),
                (
                    "name_uz",
                    models.CharField(max_length=100, verbose_name="Название (узб)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активен"), ("archived", "Архив")],
                        default="active",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Вид яиц",
                "verbose_name_plural": "Виды яиц",
                "db_table": "egg_types",
                "ordering": ["name_ru"],
            },
        ),
        migrations.CreateModel(
            name="KVStore",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("value", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Значение (KV)",
                "verbose_name_plural": "KV-хранилище",
                "db_table": "kv_store",
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_per_tray",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Цена за лоток"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="Действует с",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Установил",
                    ),
                ),
                (
                    "egg_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="catalog.eggtype",
                        verbose_name="Вид яиц",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена",
                "verbose_name_plural": "История цен",
                "db_table": "prices",
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название фирмы/магазина"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Контактное лицо"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="Телефон"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Адрес / ориентир"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Заметка")),
                (
                    "is_archived",
                    models.BooleanField(default=False, verbose_name="В архиве"),
                ),
                (
                    "opening_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Начальный долг",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shops",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Магазин (клиент)",
                "verbose_name_plural": "Магазины (клиенты)",
                "db_table": "shops",
                "ordering": ["name"],
            },
        ),
    ]
