# Generated by Django 5.1.15 on 2026-07-09 19:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator_label",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Оператор (текст)"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Создание"),
                            ("update", "Изменение"),
                            ("cancel", "Аннулирование"),
                            ("login", "Вход"),
                            ("other", "Прочее"),
                        ],
                        default="other",
                        max_length=16,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(blank=True, max_length=64, verbose_name="Объект"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="ID объекта"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Изменённые поля"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="catalog.shop",
                        verbose_name="Магазин",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись журнала",
                "verbose_name_plural": "Журнал действий",
                "db_table": "activity_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Adjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Плюс увеличивает долг, минус — уменьшает",
                        max_digits=14,
                        verbose_name="Сумма (±)",
                    ),
                ),
                ("reason", models.CharField(max_length=300, verbose_name="Причина")),
                ("message", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Аннулирована"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Администратор",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="catalog.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корректировка долга",
                "verbose_name_plural": "Корректировки долга",
                "db_table": "adjustments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата оплаты"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Сумма оплаты"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Наличные"), ("card", "Карта / Перевод")],
                        default="cash",
                        max_length=8,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Комментарий"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Изменена"),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Аннулирована"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата аннулирования"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Аннулировал",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Оператор",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="catalog.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приём оплаты",
                "verbose_name_plural": "Приёмы оплаты",
                "db_table": "payments",
                "ordering": ["-operation_date"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата продажи"
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Итого к оплате",
                    ),
                ),
                (
                    "received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Получено денег",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Наличные"), ("card", "Карта / Перевод")],
                        default="cash",
                        max_length=8,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Комментарий"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Изменена"),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Аннулирована"),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата аннулирования"
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Причина аннулирования"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_sales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Аннулировал",
                    ),
                ),
                (
                    "deliverer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Доставщик",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="catalog.shop",
                        verbose_name="Магазин",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажа",
                "verbose_name_plural": "Продажи",
                "db_table": "sales",
                "ordering": ["-operation_date"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[("tray", "Лоток"), ("box", "Коробка")],
                        default="box",
                        max_length=8,
                        verbose_name="Единица",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Количество"
                    ),
                ),
                (
                    "price_per_tray",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        verbose_name="Цена за лоток (снимок)",
                    ),
                ),
                (
                    "trays",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Лотков всего"
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Сумма строки"
                    ),
                ),
                (
                    "egg_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="catalog.eggtype",
                        verbose_name="Вид яиц",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="operations.sale",
                        verbose_name="Продажа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция продажи",
                "verbose_name_plural": "Позиции продажи",
                "db_table": "sale_items",
            },
        ),
    ]
