# Generated by Django 5.1.15 on 2026-07-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Клик / Карта'), ('transfer', 'Перечисление')], default='cash', max_length=8, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Клик / Карта'), ('transfer', 'Перечисление')], default='cash', max_length=8, verbose_name='Способ оплаты'),
        ),
    ]
