# Generated by Django 5.1.15 on 2026-07-17 16:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_shop_latitude_shop_longitude'),
        ('operations', '0002_alter_payment_payment_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество (штук)')),
                ('operation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата возврата')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('message', models.TextField(blank=True, verbose_name='Описание')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменена')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Аннулирована')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата аннулирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_returns', to=settings.AUTH_USER_MODEL, verbose_name='Аннулировал')),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to=settings.AUTH_USER_MODEL, verbose_name='Доставщик')),
                ('egg_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='catalog.eggtype', verbose_name='Вид яиц')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='catalog.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Возврат (возмещение)',
                'verbose_name_plural': 'Возвраты (возмещения)',
                'db_table': 'returns',
                'ordering': ['-operation_date'],
            },
        ),
    ]
