# Generated by Django 5.1.15 on 2026-07-19 07:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма расхода')),
                ('category', models.CharField(choices=[('lunch', 'Обед'), ('other', 'Прочее')], default='other', max_length=8, verbose_name='Категория')),
                ('operation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата расхода')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('message', models.TextField(blank=True, verbose_name='Описание')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Изменена')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Аннулирована')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата аннулирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Аннулировал')),
                ('deliverer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Доставщик')),
            ],
            options={
                'verbose_name': 'Расход доставщика',
                'verbose_name_plural': 'Расходы доставщиков',
                'db_table': 'expenses',
                'ordering': ['-operation_date'],
            },
        ),
    ]
